### PR TITLE
Avoid front panel port handling on recirc port

### PR DESCRIPTION
**Pull request by ysmanman**
Recirc port is not used as front panel port. So avoid front panel port handling on recirc port.

### CODE REVIEW

**Comment by prgeor** [comment]
@ysmanman are you still looking for this change? can you fix the conflict?

**Comment by ysmanman** [comment]
> @ysmanman are you still looking for this change? can you fix the conflict?

@prgeor Sure, I will resolve the conflict.

**Comment by ysmanman** [comment]
> > @ysmanman are you still looking for this change? can you fix the conflict?
> 
> @prgeor Sure, I will resolve the conflict.

@prgeor It seems https://github.com/Azure/sonic-platform-common/pull/251 was already merged. So this PR is not required anymore.

**Pull request closed without merging**
