### PR TITLE
[sonic_sfp] Extend sfpbase to get more info from SFP eeprom for xcvrd

### PR DESCRIPTION
**Pull request by keboliu**
```
sonic_sfp: Extend sfputilbase to support xcvrd get more fields from SFP eeprom.

* Extends sff8446 and sff8472 with more fields parsing functions.
* Extend sfputilbase to return more fields to xcvrd.
* Add handling for OSFP. 
  
  Signed-off-by: Kebo Liu kebol@mellanox.com

```

### CODE REVIEW

**Comment by jleveque** [comment]
Please fix conflicts.

**Comment by keboliu** [comment]
do not merge first, need to handle new added  OSFP.

**Comment by keboliu** [comment]
@jleveque  conflicts fixed and added special treatment for OSFP to avoid xcvrd fail. OSFP transceiver info memory map not fully defined in newly added inf8628.py,  it's also lack of DOM memory map definition. Since I don't have a platform that supports OSFP, I would like to add the fully support for it later or someone can also add it.

**Comment by keboliu** [comment]
@lguohan joe requesting you for a review, would you please take a look.

**Comment by liat-grozovik** [comment]
@lguohan can you please review?

**Pull request merged**
