### PR TITLE
Add parser support for Tx_RxLos,TxFault, PowerControl, ResetStatus in sff8436.py

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
Pull Request to add parser support for the following data in sff8436.py file

DataNotReady,
TxLos,
RxLos,
TxFault,
TxDisable,
Power Control

Also implement new api get_transceiver_threshold_info to retrieve EEPROM Dom Threshold Values.

### CODE REVIEW

**Comment by keboliu** [comment]
the enhance looks good to me, one thing is that can you make **sonic_sfp** as a symbolic link to **sonic_platform_base/sonic_sfp** so we don't need to maintain the duplicated files?

**Comment by sridhar-ravindran** [comment]
Hi @keboliu 
I see may diff between directories.
$sonic-platform-common>diff sonic_sfp/ sonic_platform_base/sonic_sfp/ > diff_between_dirs

Attached the diff file.  Since it involves lot of changes, can we clean it up via another pull request ?

Thanks
Sridhar.R
[diff_between_dirs.txt](https://github.com/Azure/sonic-platform-common/files/3426126/diff_between_dirs.txt)

**Comment by keboliu** [comment]
> Hi @keboliu
> I see may diff between directories.
> $sonic-platform-common>diff sonic_sfp/ sonic_platform_base/sonic_sfp/ > diff_between_dirs
> 
> Attached the diff file. Since it involves lot of changes, can we clean it up via another new pull request ?
> 
> Thanks
> Sridhar.R
> [diff_between_dirs.txt](https://github.com/Azure/sonic-platform-common/files/3426126/diff_between_dirs.txt)

OK.

**Comment by sridhar-ravindran** [comment]
Hi @jleveque  @keboliu 

Thanks for the approval.  
Request you to merge the changes.

**Pull request merged**
