### PR TITLE
[sonic_ssd] Nokia-7215: "show platform ssdhealth" not showing health percent

### PR DESCRIPTION
**Pull request by bill-nokia**
#### Description

The command is not showing the correct value for ssd health.
```
admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : N/A
Temperature  : 25C
```
#### Motivation and Context

SSD health percentage not displayed on Nokia-7215 platform.

#### How Has This Been Tested?

"show platform ssdhealth" cli command
Output after fix:
```
admin@sonic:~$ show platform ssdhealth 
Device Model : M.2 (S42) 3IE4
Health       : 100%
Temperature  : 25C
```

### CODE REVIEW

**Comment by carl-nokia** [comment]
@sujinmkang hoping to get this in for future release, multiple merges required including 202012

**Comment by Blueve** [comment]
@carl-nokia  do you want to backport this change to 202012 and 202111 only?

**Comment by carl-nokia** [comment]
@Blueve --yes - please backport this change to 202012 and 202111

**Comment by Blueve** [comment]
Hi @carl-nokia , can you address above comments?

**Comment by bill-nokia** [comment]
@Blueve  @sujinmkang I added a commit on May 5th to address the comments above. Let me know if it needs to be updated

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
