### PR TITLE
[psu_base] get_status_led() returns current state of the status LED

### PR DESCRIPTION
**Pull request by jleveque**
- Also add the same function to fan_base.py.

### CODE REVIEW

**Comment by jleveque** [comment]
> In psu.py, please add AMBER in the color list.

Added `STATUS_LED_COLOR_AMBER` to both psu_base and fan_base.

> Also, is it better to rename those variables " STATUS_LED_COLOR_GREEN" as "PSU_STATUS_LED_COLOR_GREEN". This way,we can keep separate variables for FAN LEDs and separate variables for front panel LEDs. For example, in case of front panel LEDs, blue color is also valid, which is invalid in case of power LEDs.

I feel this is unnecessary since these are class members. They need to be accessed by referencing the class (e.g., `this.STATUS_LED_COLOR_GREEN`, `my_fan.STATUS_LED_COLOR_GREEN`, etc.). I feel it is better to cover all bases, so each list should contain all possibilities. We may also want to just make one list and share it among all device classes which can control LEDs.

**Comment by kannankvs** [comment]
'''Joe:I would ask if it makes sense to add a flashing rate parameter to specify the frequency with which it should flash?'''
Flashing rate may not be important for the caller.

**Comment by jleveque** [comment]
@kannankvs: Do you have an opinion on the tuple vs. new "colors" approach I proposed above?

**Comment by kannankvs** [comment]
>> Joe: @kannankvs: Do you have an opinion on the tuple vs. new "colors" approach I proposed above?
Tuple is better. Even there is a need to add one or two new colors to the colors_list or if there is a need to add one other flashing status in future,  it will be easier if we use "tuple". In general, we always prefer two different information in two different variables instead of combining them in a single variable.

**Comment by jleveque** [comment]
@kannankvs: Understood. Then I must ask, do you think it's better to denote "off" as a "color" as it is now, or as a state (e.g., `STATUS_LED_STATE_OFF`, `STATUS_LED_STATE_ON_SOLID`, `STATUS_LED_STATE_ON_FLASHING`)?

**Comment by kannankvs** [comment]
@jleveque OFF is a state like "Solid", "Blinking". I missed to see that OFF in the list.

**Comment by jleveque** [comment]
@kannankvs: I think the change to a tuple that you've requested should be dealt with in a separate PR. Would you be willing to make that change? If so, let's get this PR approved and merged first.

**Comment by kannankvs** [comment]
@jleveque : OK, we will do it. Once if this PR is merged, we will raise PR for the tuple.

**Comment by jleveque** [comment]
@kannankvs: Sounds good. Pleas approve this PR if you are OK with it.

**Comment by kannankvs** [comment]
@jleveque : Approvals done. Thank you.

**Pull request merged**
