### PR TITLE
Write the contents of EEPROM to database

### PR DESCRIPTION
**Pull request by kevinwangsk**
Add two new function update_eeprom_db() and read_eeprom_db() to support
update and print EEPROM information from redis database directly.

Signed-off-by: Kevin Wang <kevinw@mellanox.com>

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@kevinwangsk can you please update the commit message to the 'template' recently used?
@jleveque can you please refer to the changes requested ?

**Comment by kevinwangsk** [comment]
> @kevinwangsk can you please update the commit message to the 'template' recently used?
Done
> @jleveque can you please refer to the changes requested ?

**Comment by jleveque** [comment]
@liat-grozovik: I don't quite understand your request. Could you please be more specific?

**Comment by kevinwangsk** [comment]
Any more comments here before we merge this PR?

**Comment by jleveque** [comment]
No further comments here.

**Pull request merged**
