### PR TITLE
Load policy interval from thermal_policy.json

### PR DESCRIPTION
**Pull request by andywongarista**
#### Description

Update ThermalManagerBase to load an interval field from thermal_policy.json if it is available and provide a getter for this interval.

#### Motivation and Context

This interval can be used by thermalctld to run policies at an interval specified in thermal_policy.json, rather than a fixed constant (currently 60 seconds).

#### How Has This Been Tested?

Verified that thermalctld runs without exiting.
Also ran test_thermalctld.py

### CODE REVIEW

**Comment by jleveque** [comment]
@Junchao-Mellanox: Please review.

**Comment by jleveque** [comment]
@andywongarista: Please fix new conflicts.

**Comment by jleveque** [comment]
@Junchao-Mellanox: Please review.

**Review by sujinmkang — APPROVED** [review]
looks good to me!

**Pull request merged**
