### PR TITLE
Changes in fan and psu base classes (1.0 platform API) related to pddf_2.0

### PR DESCRIPTION
**Pull request by fk410167**
Small changes in 1.0 platform plugins psu_base.py and fan_base.py. Changes are related to PDDF 2.0 changes. 
psu_base.py:
 - psu_fan speed API name change 
 - Changing the voltage, current and power units to 
fan_base.py:
 - Individual fans are counted instead of fantrays units
 - get_speed_rear() is not required

Depends on:
https://github.com/Azure/SONiC/pull/536

### CODE REVIEW

**Comment by jleveque** [comment]
@fk410167: What do you mean by "1.0 platform plugins"? The files you modified are part of the platform API 2.0; they are not version 1.0 "plugins".

**Comment by jleveque** [comment]
@fk410167: Can you please explain how modifying the API version 1.0 plugins is related to adding support for 2.0 platform APIs?

**Comment by fk410167** [comment]
2.0 APIs are supported in PDDF. However, some platforms still support old
plugins. We added extra attributes to these plugins in previous PDDF PRs.
Till now, these extra plugin methods were used only from PDDF utils.

There has been a need of minor changes in those extra plugin methods as per
the current PDDF utilities. E.g. the type of variable of voltage, current
and power.

-Fuzail

**Comment by fk410167** [comment]
The changes are made in the base class of old plugins. e.g.
sonic_psu/psu_base.py
 ( not the 2.0 base class sonic_platform_base/psu_base.py)


-Fuzail

**Comment by xinliu-seattle** [comment]
@jleveque can you please merge it? thanks

**Pull request merged**
